// config-pg.ts 现在是桶文件，所有实现已迁移到 src/services/config/ 目录。
// 保持此文件以兼容现有 import 路径。

export type { AgentFullConfig, UserConfigData } from "./config/index";
export {
  AGENT_SETTABLE_FIELDS,
  addModel,
  createAgentConfig,
  createMcpServer,
  deleteAgentConfig,
  deleteMcpServer,
  deleteProvider,
  deleteSkill,
  disableSkill,
  enableSkill,
  getAgentConfig,
  getAgentConfigById,
  getAgentFullConfig,
  getMcpServer,
  getProvider,
  getSkill,
  getUserConfig,
  listAgentConfigs,
  listMcpServers,
  listProviders,
  listSkills,
  listWorkspaceSkills,
  removeModel,
  setMcpServerEnabled,
  setUserConfig,
  updateAgentConfig,
  updateMcpServer,
  updateModel,
  upsertProvider,
  upsertSkill,
  listAgentSkillIds,
  syncAgentSkills,
} from "./config/index";
